version: '3.12'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - mynetwork

  recipebrowser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - mynetwork
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate #Fixed Ollama URL

networks:
  mynetwork:
